### ISSUE TITLE
Upload Property for second record not saving image path

### ISSUE THREAD

**Issue by Katalisfire** [kgiszewski/ArchetypeManual#4]
I have a problem with my second row of the object not saving the image when i try to upload it.
The first record's image saves just fine.

![image](https://cloud.githubusercontent.com/assets/20534500/24202373/824283fe-0f1b-11e7-992a-bf64d4158b76.png)

![image](https://cloud.githubusercontent.com/assets/20534500/24202426/a30d6c2a-0f1b-11e7-8fae-04e3f347341c.png)

As you can see even when upload they are not the same one shows thumbnail and the other doesnt. So with the remove files checkbox

**Comment by kgiszewski** [comment]
Please log issues over here: https://github.com/kgiszewski/Archetype
